Class {
	#name : #BIUseForTestWithMethod,
	#superclass : #Object,
	#instVars : [
		'biChooseMethod'
	],
	#category : #'MigratePrettyPrinterUI-Tests'
}

{ #category : #'as yet unclassified' }
BIUseForTestWithMethod >> ahhhhhhhhhhhhhhh [

]

{ #category : #'as yet unclassified' }
BIUseForTestWithMethod >> banane [
]

{ #category : #'as yet unclassified' }
BIUseForTestWithMethod >> leonNettoyeur [
]

{ #category : #'as yet unclassified' }
BIUseForTestWithMethod >> pommeDeTerre [
]
