Class {
	#name : #BIUseForTest,
	#superclass : #Object,
	#category : #'MigratePrettyPrinterUI-Tests'
}

{ #category : #settings }
BIUseForTest class >> basicConfig [ 
	^ BIPrettyPrinterContext new
]

{ #category : #settings }
BIUseForTest class >> config1 [ 
	^ BIPrettyPrinterContext new
]

{ #category : #methods }
BIUseForTest class >> kklm [
]

{ #category : #methods }
BIUseForTest class >> ko [
]
